services:
  test_app:
    container_name: fastapi_docker_api
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    tty: true
    command: >
      /bin/sh -c '
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      '
    environment:
      DATABASE_URL: mysql://mysql:mysql@localhost:3306/mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DB: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    depends_on:
      - test_db


  test_db:
    container_name: ${MYSQL_HOST}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - "TZ=Asia/Tokyo" # タイムゾーンを日本時刻に設定
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: