services:
  test_app:
    container_name: fastapi_docker_api
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    tty: true
    command: >
      /bin/sh -c '
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      '
