services:
  test_app:
    container_name: fastapi_docker_api
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    tty: true
    command: >
      /bin/sh -c '
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      '
    environment:
      DATABASE_URL: mysql://mysql:mysql@localhost:3306/mysql
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DB: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql


# volumes:
#   mysql-data: 


#   test_db:
#     container_name: fastapi_docker_db
#     image: MySQL:latest
#     platform: linux/x86_64
#     restart: unless-stopped
#     volumes: 
#       - mysql_data:var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: mysql
#       MYSQL_DB: mysql
#       MYSQL_USER: mysql
#       MYSQL_PASSWORD: mysql
#       MYSQL_CHARACTER_SET_SERVER: 'utf8mb4'
#       MYSQL_COLLATION_SERVER: 'utf8mb4_unicode_ci'
#     ports: 
#       - 3306:3306
