services:
  test_app:
    container_name: fastapi_docker_api
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    tty: true
    command: >
      /bin/sh -c '
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      '
    environment:
      DATABASE_URL: mysql://mysql:mysql@localhost:3306/mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DB: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    depends_on:
      - test_db


  test_db:
    container_name: fastapi_docker_db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DB: "todo"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
      MYSQL_CHARACTER_SET_SERVER: 'utf8mb4'
      MYSQL_COLLATION_SERVER: 'utf8mb4_unicode_ci'
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: